name: Build

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  build_java:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
          build-root-directory: java

  test_python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Cache Poetry virtualenv
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
            ~/.cache/pypoetry/cache
          key: poetry-${{ runner.os }}-${{ hashFiles('python/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-
      - name: Install dependencies
        run: |
          cd python
          poetry install --no-interaction --no-root
      - name: Run tests
        run: |
          cd python
          poetry run pytest
